### ISSUE TITLE
Issue with ESM module

### ISSUE THREAD

**Issue by birkskyum** [geoapify/geocoder-autocomplete#6]
Version 1.3.4 is working, version >=1.4.1 isn't. When using the package from a project with package.json having type: module, this library breaks. 

It's attempting to load
An unhandled error occured: .../node_modules/@geoapify/geocoder-autocomplete/dist/index.js:1

export { GeocoderAutocomplete } from './autocomplete';
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1033:15)
    at Module._compile (node:internal/modules/cjs/loader:1069:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    
    
    I can see that there is an index.min.esm.js file, but it never seem to be in use.

# Repro steps

```bash
# create a new project in the current directory
npm create solid

Name? geoapify-repro
TypeScritp? yes
Example? bare


npm i @geoapify/geocoder-autocomplete
```

Inside src/routes/app.ts, import and log it (if not logged, the unused import will be removed):

```ts
import { createSignal } from "solid-js";
import { GeocoderAutocomplete } from "@geoapify/geocoder-autocomplete";
import "./app.css";

export default function App() {
  console.log(GeocoderAutocomplete)
  const [count, setCount] = createSignal(0);

  return (
    <main>
      <h1>Hello world!</h1>
      <button class="increment" onClick={() => setCount(count() + 1)} type="button">
        Clicks: {count()}
      </button>
      <p>
        Visit{" "}
        <a href="https://start.solidjs.com" target="_blank">
          start.solidjs.com
        </a>{" "}
        to learn how to build SolidStart apps.
      </p>
    </main>
  );
}
```

Run:
`npm run dev`

**Comment by banexxl** [comment]
I have the same issue :(

**Comment by ki7** [comment]
Hello same here

**Comment by patrikengborg** [comment]
I have the same problem. Is this project abandoned or what's going on?

**Comment by birkskyum** [comment]
a lot happened a month ago, so there's still hope.

**Comment by birkskyum** [comment]
Did you try v2 that was released?

**Comment by Targetx25** [comment]
Hey, I am also Having the  same issue currently..Any Solutions?

**Comment by birkskyum** [comment]
@Targetx25 , what version did you use?

**Comment by Targetx25** [comment]
> @Targetx25 , what version did you use?

I am using 2.0.1..Seems like they didn't fixed it at all

**Comment by birkskyum** [comment]
**Repro steps**

```bash
# create a new project in the current directory
npm create solid

Name? geoapify-repro
TypeScritp? yes
Example? bare


npm i @geoapify/geocoder-autocomplete
```

Inside src/routes/app.ts, import and log it (if not logged, the unused import will be removed):

```ts
import { createSignal } from "solid-js";
import { GeocoderAutocomplete } from "@geoapify/geocoder-autocomplete";
import "./app.css";

export default function App() {
  console.log(GeocoderAutocomplete)
  const [count, setCount] = createSignal(0);

  return (
    <main>
      <h1>Hello world!</h1>
      <button class="increment" onClick={() => setCount(count() + 1)} type="button">
        Clicks: {count()}
      </button>
      <p>
        Visit{" "}
        <a href="https://start.solidjs.com" target="_blank">
          start.solidjs.com
        </a>{" "}
        to learn how to build SolidStart apps.
      </p>
    </main>
  );
}
```

Run:
`npm run dev`
